# Generated by Django 5.2.4 on 2025-08-29 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_twitteraccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_usernames', models.JSONField(default=list, help_text='List of Twitter usernames to target followers')),
                ('target_post_urls', models.JSONField(default=list, help_text='List of Twitter post URLs to target commenters')),
                ('operation_type', models.CharField(choices=[('AND', 'AND - All conditions must match'), ('OR', 'OR - Any condition can match')], default='AND', max_length=3)),
                ('min_followers', models.IntegerField(default=0)),
                ('max_followers', models.IntegerField(default=1000000)),
                ('locations', models.JSONField(blank=True, default=list, help_text='List of target locations')),
                ('bio_keywords', models.JSONField(blank=True, default=list, help_text='Keywords to match in bio')),
                ('exclude_keywords', models.JSONField(blank=True, default=list, help_text='Keywords to exclude from bio')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTING', 'Collecting'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('total_collected', models.IntegerField(default=0)),
                ('max_leads', models.IntegerField(default=1000000)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('current_batch_user', models.CharField(blank=True, max_length=100, null=True)),
                ('current_batch_offset', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweet_count', models.IntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('FOLLOWER', 'Follower'), ('COMMENTER', 'Commenter')], max_length=20)),
                ('source_reference', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='main.leadlist')),
            ],
            options={
                'unique_together': {('lead_list', 'username')},
            },
        ),
    ]
