# Generated by Django 5.2.4 on 2025-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_leadlist_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='pagination_state',
            field=models.JSONField(default=dict, help_text='Stores pagination state for each target (usernames, post URLs)'),
        ),
    ]
