# Generated by Django 5.2.4 on 2025-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_leadlist_pagination_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_list', 'username'], name='lead_list_username_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_list', 'created_at'], name='lead_list_created_idx'),
        ),
    ]
