# Generated by Django 5.2.4 on 2025-08-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lead_lead_list_username_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadlist',
            name='operation_type',
        ),
    ]
