# Generated by Django 5.2.4 on 2025-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_leadlist_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='estimated_total_leads',
            field=models.IntegerField(default=0, help_text='Estimated total leads available based on followers found'),
        ),
    ]
